#!/bin/bash

POD="$1"
if kubectl exec -it "$POD" -- test -x /bin/bash > /dev/null 2>&1; then
  COMMAND="/bin/bash"
else
  COMMAND="/bin/sh"
fi

BLUE='\033[0;34m'
LBLUE='\033[1;34m'
NC='\033[0m'
echo -e "${BLUE}Running ${LBLUE}$COMMAND${BLUE} in ${LBLUE}$POD${NC}"
kubectl exec "$POD" -it -- $COMMAND
